# Generated by Django 6.0.3 on 2026-03-27 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_photos/'),
        ),
        migrations.CreateModel(
            name='ResidentPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approves', models.BooleanField(help_text='Whether the resident currently approves living here.')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_pulses', to='api.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
