# Generated by Django 6.0.3 on 2026-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_image_residentpulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lease_insight',
            field=models.TextField(blank=True, help_text='Demo narrative about what renters often watch for in the lease.'),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_type_hint',
            field=models.CharField(blank=True, help_text='Demo hint about typical lease structure; not verified.', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='management_insight',
            field=models.TextField(blank=True, help_text='Demo narrative about how management tends to operate (sample only).'),
        ),
    ]
